### ISSUE TITLE
running it on tensorRT 10.3.0 and cuda 11.5

### ISSUE THREAD

**Issue by sourav-bz** [zhujiajian98/Depth-Anythingv2-TensorRT-python#1]
hey i am trying to run the code on tensorRT 10.3.0, python3.10, cuda 11.5 running on Ubuntu 22.
I was able to convert the onnx to .engine with the help of claude. but i am not able to run and test using dpt.py facing bunch of errors with the tensorRT version conflict, can you help me out here?

**Comment by zhujiajian98** [comment]
@sourav-bz Hello, have you solve it?
